import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// Importing Components
import Layout from '../components/layout';
import Hero from '../components/Hero'

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Hero/>
        </main>
      </div>
    </Layout>
  )
}
